# This file was generated by GoReleaser. DO NOT EDIT.
cask "context-zero" do
  name "context-zero"
  desc "Context-Zero: Reachability-aware context generator for LLMs."
  homepage "https://context-zero.dev"
  version "0.1.18"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "context-zero"

  on_linux do
    on_intel do
      url "https://github.com/astrabyte-tech/context-zero-releases/releases/download/v#{version}/context-zero_#{version}_linux_amd64.tar.gz"
      sha256 "263c421eef58b180f499920e438d2e5528cf823e8c9d76fa5fc9b1739b53d4d7"
    end
    on_arm do
      url "https://github.com/astrabyte-tech/context-zero-releases/releases/download/v#{version}/context-zero_#{version}_linux_arm64.tar.gz"
      sha256 "611259b11b7ca95df55dd2ab6d90e4867e17e08ad9689719a34d7f06900a6462"
    end
  end

  # No zap stanza required
end
