# This file was generated by GoReleaser. DO NOT EDIT.
cask "context-zero" do
  name "context-zero"
  desc "Context-Zero: Reachability-aware context generator for LLMs."
  homepage "https://context-zero.dev"
  version "1.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "context-zero"

  on_linux do
    on_intel do
      url "https://github.com/astrabyte-tech/context-zero-releases/releases/download/v#{version}/context-zero_#{version}_linux_amd64.tar.gz"
      sha256 "3ed10bff43257e013177a4aaa30b3d62dc02ec99bd1be74bac45c9d961356229"
    end
    on_arm do
      url "https://github.com/astrabyte-tech/context-zero-releases/releases/download/v#{version}/context-zero_#{version}_linux_arm64.tar.gz"
      sha256 "6e24ee242c33706273c778de109c9fd72ef5479f925418c037db605ab697b884"
    end
  end

  # No zap stanza required
end
