# This file was generated by GoReleaser. DO NOT EDIT.
cask "context-zero" do
  name "context-zero"
  desc "Context-Zero: Reachability-aware context generator for LLMs."
  homepage "https://context-zero.dev"
  version "0.1.16"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "context-zero"

  on_linux do
    on_intel do
      url "https://github.com/astrabyte-tech/context-zero/releases/download/v#{version}/context-zero_#{version}_linux_amd64.tar.gz"
      sha256 "2e758874076bc151aa7ef3190851d7a4874a83ad5221ee97810a7c6f4bd43408"
    end
    on_arm do
      url "https://github.com/astrabyte-tech/context-zero/releases/download/v#{version}/context-zero_#{version}_linux_arm64.tar.gz"
      sha256 "4fb4456f1c7ec0650aac61c950d3b4e0ce1220ce72660d273f0b6efbe4ba91f5"
    end
  end

  # No zap stanza required
end
